name: alumni-feup

services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: alumni-feup-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - alumni_feup_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alumni_feup_network

  redis:
    image: redis:7
    container_name: alumni-feup-redis
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alumni_feup_network

volumes:
  alumni_feup_postgres_data:

networks:
  alumni_feup_network:
    driver: bridge
