/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Alumni
 */
export interface Alumni {
    /**
     * The id of the alumni
     * @type {string}
     * @memberof Alumni
     */
    'id': string;
    /**
     * The first name of the alumni
     * @type {string}
     * @memberof Alumni
     */
    'first_name': string;
    /**
     * The last name of the alumni
     * @type {string}
     * @memberof Alumni
     */
    'last_name': string;
    /**
     * The linkedin url of the alumni
     * @type {string}
     * @memberof Alumni
     */
    'linkedin_url'?: string;
    /**
     * The profile picture of the alumni
     * @type {object}
     * @memberof Alumni
     */
    'profile_picture_url'?: object;
    /**
     * The roles of the alumni
     * @type {Array<Role>}
     * @memberof Alumni
     */
    'roles'?: Array<Role>;
    /**
     * The current location of the alumni
     * @type {object}
     * @memberof Alumni
     */
    'Location'?: object;
    /**
     * The graduation status(es) of the alumni
     * @type {Array<Graduation>}
     * @memberof Alumni
     */
    'Graduations'?: Array<Graduation>;
}
/**
 * 
 * @export
 * @interface Course
 */
export interface Course {
    /**
     * The name of the course
     * @type {string}
     * @memberof Course
     */
    'name': string;
    /**
     * The acronym of the course
     * @type {string}
     * @memberof Course
     */
    'acronym': string;
}
/**
 * 
 * @export
 * @interface CourseExtended
 */
export interface CourseExtended {
    /**
     * The name of the course
     * @type {string}
     * @memberof CourseExtended
     */
    'name': string;
    /**
     * The acronym of the course
     * @type {string}
     * @memberof CourseExtended
     */
    'acronym': string;
    /**
     * The id of the course
     * @type {string}
     * @memberof CourseExtended
     */
    'id': string;
    /**
     * The start year of the course
     * @type {number}
     * @memberof CourseExtended
     */
    'start_year': number;
    /**
     * The end year of the course, if it is not active
     * @type {object}
     * @memberof CourseExtended
     */
    'end_year'?: object;
    /**
     * The status of the course
     * @type {string}
     * @memberof CourseExtended
     */
    'status': string;
    /**
     * The faculty id of the course
     * @type {string}
     * @memberof CourseExtended
     */
    'faculty_id': string;
    /**
     * The name of the course in the international language
     * @type {object}
     * @memberof CourseExtended
     */
    'name_int'?: object;
    /**
     * The type of the course
     * @type {string}
     * @memberof CourseExtended
     */
    'course_type': string;
}
/**
 * 
 * @export
 * @interface CreateAlumniDto
 */
export interface CreateAlumniDto {
    /**
     * The first name of the alumni
     * @type {string}
     * @memberof CreateAlumniDto
     */
    'first_name': string;
    /**
     * The last name of the alumni
     * @type {string}
     * @memberof CreateAlumniDto
     */
    'last_name': string;
    /**
     * The LinkedIn URL of the alumni
     * @type {string}
     * @memberof CreateAlumniDto
     */
    'linkedin_url': string;
    /**
     * The institutional email of the alumni
     * @type {string}
     * @memberof CreateAlumniDto
     */
    'institutional_email'?: string;
    /**
     * The personal email of the alumni
     * @type {string}
     * @memberof CreateAlumniDto
     */
    'personal_email'?: string;
    /**
     * Application specific person ID
     * @type {string}
     * @memberof CreateAlumniDto
     */
    'person_id'?: string;
    /**
     * The creator of the alumni
     * @type {string}
     * @memberof CreateAlumniDto
     */
    'created_by': string;
}
/**
 * 
 * @export
 * @interface GeoJSONFeature
 */
export interface GeoJSONFeature {
    /**
     * 
     * @type {string}
     * @memberof GeoJSONFeature
     */
    'type': string;
    /**
     * 
     * @type {object}
     * @memberof GeoJSONFeature
     */
    'geometry': object;
    /**
     * 
     * @type {object}
     * @memberof GeoJSONFeature
     */
    'properties': object;
}
/**
 * 
 * @export
 * @interface GeoJSONFeatureCollection
 */
export interface GeoJSONFeatureCollection {
    /**
     * 
     * @type {string}
     * @memberof GeoJSONFeatureCollection
     */
    'type': string;
    /**
     * 
     * @type {Array<GeoJSONFeature>}
     * @memberof GeoJSONFeatureCollection
     */
    'features': Array<GeoJSONFeature>;
}
/**
 * 
 * @export
 * @interface Graduation
 */
export interface Graduation {
    /**
     * The status of the graduation
     * @type {string}
     * @memberof Graduation
     */
    'status': string;
    /**
     * The conclusion year of the graduation
     * @type {object}
     * @memberof Graduation
     */
    'conclusion_year': object;
    /**
     * The course of the graduation
     * @type {Course}
     * @memberof Graduation
     */
    'Course': Course;
}
/**
 * 
 * @export
 * @interface LinkedinAuthDto
 */
export interface LinkedinAuthDto {
    /**
     * A unique identifying value for the member. Referenced as personId in other API documentation pages.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    'person_id': string;
    /**
     * The first name of the member.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    'first_name': string;
    /**
     * The first name of the member.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    'last_name': string;
    /**
     * The personal email of the member.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    'institutional_email'?: string;
    /**
     * The URL of the member\'s profile picture.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    'profile_picture_url'?: string;
}
/**
 * 
 * @export
 * @interface Role
 */
export interface Role {
    /**
     * The id of the role
     * @type {string}
     * @memberof Role
     */
    'id': string;
    /**
     * The id of the alumni
     * @type {string}
     * @memberof Role
     */
    'alumni_id': string;
    /**
     * The id of the company
     * @type {string}
     * @memberof Role
     */
    'company_id': string;
    /**
     * The start date of the role
     * @type {string}
     * @memberof Role
     */
    'start_date': string;
    /**
     * The end date of the role
     * @type {object}
     * @memberof Role
     */
    'end_date'?: object | null;
    /**
     * The seniority level of the role
     * @type {string}
     * @memberof Role
     */
    'seniority_level': string;
    /**
     * The level 1 of the role
     * @type {string}
     * @memberof Role
     */
    'esco_l1': string;
    /**
     * The level 2 of the role
     * @type {string}
     * @memberof Role
     */
    'esco_l2': string;
}
/**
 * 
 * @export
 * @interface UploadExtractionDto
 */
export interface UploadExtractionDto {
    /**
     * 
     * @type {string}
     * @memberof UploadExtractionDto
     */
    'faculty_id': string;
    /**
     * 
     * @type {string}
     * @memberof UploadExtractionDto
     */
    'course_id': string;
}

/**
 * AlumniApi - axios parameter creator
 * @export
 */
export const AlumniApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new alumni
         * @param {CreateAlumniDto} createAlumniDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerCreate: async (createAlumniDto: CreateAlumniDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAlumniDto' is not null or undefined
            assertParamExists('alumniControllerCreate', 'createAlumniDto', createAlumniDto)
            const localVarPath = `/api/alumni`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAlumniDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all alumni, enriched with location, graduations and roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/alumni`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all alumni to be displayed in the map
         * @param {Array<string>} [courseIds] The ID(s) of the course(s)
         * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAllGeoJSON: async (courseIds?: Array<string>, conclusionYears?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/alumni/geoJSON`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (courseIds) {
                localVarQueryParameter['courseIds'] = courseIds;
            }

            if (conclusionYears) {
                localVarQueryParameter['conclusionYears'] = conclusionYears;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get alumni by id, enriched with location, graduations and roles
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('alumniControllerFindOne', 'id', id)
            const localVarPath = `/api/alumni/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AlumniApi - functional programming interface
 * @export
 */
export const AlumniApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AlumniApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new alumni
         * @param {CreateAlumniDto} createAlumniDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Alumni>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerCreate(createAlumniDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AlumniApi.alumniControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all alumni, enriched with location, graduations and roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Alumni>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AlumniApi.alumniControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all alumni to be displayed in the map
         * @param {Array<string>} [courseIds] The ID(s) of the course(s)
         * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeoJSONFeatureCollection>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerFindAllGeoJSON(courseIds, conclusionYears, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AlumniApi.alumniControllerFindAllGeoJSON']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get alumni by id, enriched with location, graduations and roles
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Alumni>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AlumniApi.alumniControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AlumniApi - factory interface
 * @export
 */
export const AlumniApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AlumniApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new alumni
         * @param {CreateAlumniDto} createAlumniDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni> {
            return localVarFp.alumniControllerCreate(createAlumniDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all alumni, enriched with location, graduations and roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<Alumni>> {
            return localVarFp.alumniControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all alumni to be displayed in the map
         * @param {Array<string>} [courseIds] The ID(s) of the course(s)
         * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<GeoJSONFeatureCollection> {
            return localVarFp.alumniControllerFindAllGeoJSON(courseIds, conclusionYears, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get alumni by id, enriched with location, graduations and roles
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Alumni> {
            return localVarFp.alumniControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AlumniApi - interface
 * @export
 * @interface AlumniApi
 */
export interface AlumniApiInterface {
    /**
     * 
     * @summary Create a new alumni
     * @param {CreateAlumniDto} createAlumniDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApiInterface
     */
    alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni>;

    /**
     * 
     * @summary Get all alumni, enriched with location, graduations and roles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApiInterface
     */
    alumniControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<Alumni>>;

    /**
     * 
     * @summary Get all alumni to be displayed in the map
     * @param {Array<string>} [courseIds] The ID(s) of the course(s)
     * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApiInterface
     */
    alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<GeoJSONFeatureCollection>;

    /**
     * 
     * @summary Get alumni by id, enriched with location, graduations and roles
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApiInterface
     */
    alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Alumni>;

}

/**
 * AlumniApi - object-oriented interface
 * @export
 * @class AlumniApi
 * @extends {BaseAPI}
 */
export class AlumniApi extends BaseAPI implements AlumniApiInterface {
    /**
     * 
     * @summary Create a new alumni
     * @param {CreateAlumniDto} createAlumniDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApi
     */
    public alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig) {
        return AlumniApiFp(this.configuration).alumniControllerCreate(createAlumniDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all alumni, enriched with location, graduations and roles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApi
     */
    public alumniControllerFindAll(options?: RawAxiosRequestConfig) {
        return AlumniApiFp(this.configuration).alumniControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all alumni to be displayed in the map
     * @param {Array<string>} [courseIds] The ID(s) of the course(s)
     * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApi
     */
    public alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig) {
        return AlumniApiFp(this.configuration).alumniControllerFindAllGeoJSON(courseIds, conclusionYears, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get alumni by id, enriched with location, graduations and roles
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AlumniApi
     */
    public alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return AlumniApiFp(this.configuration).alumniControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CompanyApi - axios parameter creator
 * @export
 */
export const CompanyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/company`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get company by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('companyControllerFindOne', 'id', id)
            const localVarPath = `/api/company/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CompanyApi - functional programming interface
 * @export
 */
export const CompanyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CompanyApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async companyControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.companyControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompanyApi.companyControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get company by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async companyControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.companyControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompanyApi.companyControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CompanyApi - factory interface
 * @export
 */
export const CompanyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CompanyApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.companyControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get company by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.companyControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CompanyApi - interface
 * @export
 * @interface CompanyApi
 */
export interface CompanyApiInterface {
    /**
     * 
     * @summary Get all companies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApiInterface
     */
    companyControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get company by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApiInterface
     */
    companyControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * CompanyApi - object-oriented interface
 * @export
 * @class CompanyApi
 * @extends {BaseAPI}
 */
export class CompanyApi extends BaseAPI implements CompanyApiInterface {
    /**
     * 
     * @summary Get all companies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApi
     */
    public companyControllerFindAll(options?: RawAxiosRequestConfig) {
        return CompanyApiFp(this.configuration).companyControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get company by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApi
     */
    public companyControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return CompanyApiFp(this.configuration).companyControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CourseApi - axios parameter creator
 * @export
 */
export const CourseApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all courses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/course`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a course by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('courseControllerFindOne', 'id', id)
            const localVarPath = `/api/course/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CourseApi - functional programming interface
 * @export
 */
export const CourseApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CourseApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all courses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CourseExtended>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseApi.courseControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a course by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseExtended>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CourseApi.courseControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CourseApi - factory interface
 * @export
 */
export const CourseApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CourseApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all courses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseExtended>> {
            return localVarFp.courseControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a course by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CourseExtended> {
            return localVarFp.courseControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CourseApi - interface
 * @export
 * @interface CourseApi
 */
export interface CourseApiInterface {
    /**
     * 
     * @summary Get all courses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseApiInterface
     */
    courseControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseExtended>>;

    /**
     * 
     * @summary Get a course by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseApiInterface
     */
    courseControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CourseExtended>;

}

/**
 * CourseApi - object-oriented interface
 * @export
 * @class CourseApi
 * @extends {BaseAPI}
 */
export class CourseApi extends BaseAPI implements CourseApiInterface {
    /**
     * 
     * @summary Get all courses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseApi
     */
    public courseControllerFindAll(options?: RawAxiosRequestConfig) {
        return CourseApiFp(this.configuration).courseControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a course by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CourseApi
     */
    public courseControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return CourseApiFp(this.configuration).courseControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ExtractionsApi - axios parameter creator
 * @export
 */
export const ExtractionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Upload a CSV file for faculty extractions
         * @param {UploadExtractionDto} uploadExtractionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extractionsControllerUploadFile: async (uploadExtractionDto: UploadExtractionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uploadExtractionDto' is not null or undefined
            assertParamExists('extractionsControllerUploadFile', 'uploadExtractionDto', uploadExtractionDto)
            const localVarPath = `/api/extractions/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadExtractionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExtractionsApi - functional programming interface
 * @export
 */
export const ExtractionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExtractionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Upload a CSV file for faculty extractions
         * @param {UploadExtractionDto} uploadExtractionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.extractionsControllerUploadFile(uploadExtractionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExtractionsApi.extractionsControllerUploadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExtractionsApi - factory interface
 * @export
 */
export const ExtractionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExtractionsApiFp(configuration)
    return {
        /**
         * 
         * @summary Upload a CSV file for faculty extractions
         * @param {UploadExtractionDto} uploadExtractionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.extractionsControllerUploadFile(uploadExtractionDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExtractionsApi - interface
 * @export
 * @interface ExtractionsApi
 */
export interface ExtractionsApiInterface {
    /**
     * 
     * @summary Upload a CSV file for faculty extractions
     * @param {UploadExtractionDto} uploadExtractionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExtractionsApiInterface
     */
    extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * ExtractionsApi - object-oriented interface
 * @export
 * @class ExtractionsApi
 * @extends {BaseAPI}
 */
export class ExtractionsApi extends BaseAPI implements ExtractionsApiInterface {
    /**
     * 
     * @summary Upload a CSV file for faculty extractions
     * @param {UploadExtractionDto} uploadExtractionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExtractionsApi
     */
    public extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig) {
        return ExtractionsApiFp(this.configuration).extractionsControllerUploadFile(uploadExtractionDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Authenticate a user with LinkedIn
         * @param {LinkedinAuthDto} linkedinAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLinkedinAuth: async (linkedinAuthDto: LinkedinAuthDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'linkedinAuthDto' is not null or undefined
            assertParamExists('userControllerLinkedinAuth', 'linkedinAuthDto', linkedinAuthDto)
            const localVarPath = `/api/user/linkedinAuth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(linkedinAuthDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Authenticate a user with LinkedIn
         * @param {LinkedinAuthDto} linkedinAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Alumni>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerLinkedinAuth(linkedinAuthDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.userControllerLinkedinAuth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Authenticate a user with LinkedIn
         * @param {LinkedinAuthDto} linkedinAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni> {
            return localVarFp.userControllerLinkedinAuth(linkedinAuthDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - interface
 * @export
 * @interface UserApi
 */
export interface UserApiInterface {
    /**
     * 
     * @summary Authenticate a user with LinkedIn
     * @param {LinkedinAuthDto} linkedinAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni>;

}

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI implements UserApiInterface {
    /**
     * 
     * @summary Authenticate a user with LinkedIn
     * @param {LinkedinAuthDto} linkedinAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).userControllerLinkedinAuth(linkedinAuthDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * V1Api - axios parameter creator
 * @export
 */
export const V1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new alumni
         * @param {CreateAlumniDto} createAlumniDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerCreate: async (createAlumniDto: CreateAlumniDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createAlumniDto' is not null or undefined
            assertParamExists('alumniControllerCreate', 'createAlumniDto', createAlumniDto)
            const localVarPath = `/api/alumni`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createAlumniDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all alumni, enriched with location, graduations and roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/alumni`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all alumni to be displayed in the map
         * @param {Array<string>} [courseIds] The ID(s) of the course(s)
         * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAllGeoJSON: async (courseIds?: Array<string>, conclusionYears?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/alumni/geoJSON`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (courseIds) {
                localVarQueryParameter['courseIds'] = courseIds;
            }

            if (conclusionYears) {
                localVarQueryParameter['conclusionYears'] = conclusionYears;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get alumni by id, enriched with location, graduations and roles
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('alumniControllerFindOne', 'id', id)
            const localVarPath = `/api/alumni/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/company`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get company by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('companyControllerFindOne', 'id', id)
            const localVarPath = `/api/company/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all courses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/course`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a course by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('courseControllerFindOne', 'id', id)
            const localVarPath = `/api/course/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload a CSV file for faculty extractions
         * @param {UploadExtractionDto} uploadExtractionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extractionsControllerUploadFile: async (uploadExtractionDto: UploadExtractionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uploadExtractionDto' is not null or undefined
            assertParamExists('extractionsControllerUploadFile', 'uploadExtractionDto', uploadExtractionDto)
            const localVarPath = `/api/extractions/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(uploadExtractionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Authenticate a user with LinkedIn
         * @param {LinkedinAuthDto} linkedinAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLinkedinAuth: async (linkedinAuthDto: LinkedinAuthDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'linkedinAuthDto' is not null or undefined
            assertParamExists('userControllerLinkedinAuth', 'linkedinAuthDto', linkedinAuthDto)
            const localVarPath = `/api/user/linkedinAuth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(linkedinAuthDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * V1Api - functional programming interface
 * @export
 */
export const V1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = V1ApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new alumni
         * @param {CreateAlumniDto} createAlumniDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Alumni>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerCreate(createAlumniDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.alumniControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all alumni, enriched with location, graduations and roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Alumni>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.alumniControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all alumni to be displayed in the map
         * @param {Array<string>} [courseIds] The ID(s) of the course(s)
         * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GeoJSONFeatureCollection>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerFindAllGeoJSON(courseIds, conclusionYears, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.alumniControllerFindAllGeoJSON']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get alumni by id, enriched with location, graduations and roles
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Alumni>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.alumniControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.alumniControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async companyControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.companyControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.companyControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get company by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async companyControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.companyControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.companyControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all courses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CourseExtended>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.courseControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a course by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async courseControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CourseExtended>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.courseControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.courseControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload a CSV file for faculty extractions
         * @param {UploadExtractionDto} uploadExtractionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.extractionsControllerUploadFile(uploadExtractionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.extractionsControllerUploadFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Authenticate a user with LinkedIn
         * @param {LinkedinAuthDto} linkedinAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Alumni>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userControllerLinkedinAuth(linkedinAuthDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['V1Api.userControllerLinkedinAuth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * V1Api - factory interface
 * @export
 */
export const V1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = V1ApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new alumni
         * @param {CreateAlumniDto} createAlumniDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni> {
            return localVarFp.alumniControllerCreate(createAlumniDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all alumni, enriched with location, graduations and roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<Alumni>> {
            return localVarFp.alumniControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all alumni to be displayed in the map
         * @param {Array<string>} [courseIds] The ID(s) of the course(s)
         * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<GeoJSONFeatureCollection> {
            return localVarFp.alumniControllerFindAllGeoJSON(courseIds, conclusionYears, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get alumni by id, enriched with location, graduations and roles
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Alumni> {
            return localVarFp.alumniControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.companyControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get company by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.companyControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all courses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseExtended>> {
            return localVarFp.courseControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a course by id
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        courseControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CourseExtended> {
            return localVarFp.courseControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload a CSV file for faculty extractions
         * @param {UploadExtractionDto} uploadExtractionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.extractionsControllerUploadFile(uploadExtractionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Authenticate a user with LinkedIn
         * @param {LinkedinAuthDto} linkedinAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni> {
            return localVarFp.userControllerLinkedinAuth(linkedinAuthDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * V1Api - interface
 * @export
 * @interface V1Api
 */
export interface V1ApiInterface {
    /**
     * 
     * @summary Create a new alumni
     * @param {CreateAlumniDto} createAlumniDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni>;

    /**
     * 
     * @summary Get all alumni, enriched with location, graduations and roles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    alumniControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<Alumni>>;

    /**
     * 
     * @summary Get all alumni to be displayed in the map
     * @param {Array<string>} [courseIds] The ID(s) of the course(s)
     * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<GeoJSONFeatureCollection>;

    /**
     * 
     * @summary Get alumni by id, enriched with location, graduations and roles
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Alumni>;

    /**
     * 
     * @summary Get all companies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    companyControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get company by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    companyControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get all courses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    courseControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<Array<CourseExtended>>;

    /**
     * 
     * @summary Get a course by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    courseControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CourseExtended>;

    /**
     * 
     * @summary Upload a CSV file for faculty extractions
     * @param {UploadExtractionDto} uploadExtractionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Authenticate a user with LinkedIn
     * @param {LinkedinAuthDto} linkedinAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1ApiInterface
     */
    userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig): AxiosPromise<Alumni>;

}

/**
 * V1Api - object-oriented interface
 * @export
 * @class V1Api
 * @extends {BaseAPI}
 */
export class V1Api extends BaseAPI implements V1ApiInterface {
    /**
     * 
     * @summary Create a new alumni
     * @param {CreateAlumniDto} createAlumniDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public alumniControllerCreate(createAlumniDto: CreateAlumniDto, options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).alumniControllerCreate(createAlumniDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all alumni, enriched with location, graduations and roles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public alumniControllerFindAll(options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).alumniControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all alumni to be displayed in the map
     * @param {Array<string>} [courseIds] The ID(s) of the course(s)
     * @param {Array<string>} [conclusionYears] The year(s) of conclusion(s)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public alumniControllerFindAllGeoJSON(courseIds?: Array<string>, conclusionYears?: Array<string>, options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).alumniControllerFindAllGeoJSON(courseIds, conclusionYears, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get alumni by id, enriched with location, graduations and roles
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public alumniControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).alumniControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all companies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public companyControllerFindAll(options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).companyControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get company by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public companyControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).companyControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all courses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public courseControllerFindAll(options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).courseControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a course by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public courseControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).courseControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload a CSV file for faculty extractions
     * @param {UploadExtractionDto} uploadExtractionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public extractionsControllerUploadFile(uploadExtractionDto: UploadExtractionDto, options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).extractionsControllerUploadFile(uploadExtractionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Authenticate a user with LinkedIn
     * @param {LinkedinAuthDto} linkedinAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V1Api
     */
    public userControllerLinkedinAuth(linkedinAuthDto: LinkedinAuthDto, options?: RawAxiosRequestConfig) {
        return V1ApiFp(this.configuration).userControllerLinkedinAuth(linkedinAuthDto, options).then((request) => request(this.axios, this.basePath));
    }
}



