/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlumniOptionDto
 */
export interface AlumniOptionDto {
    /**
     * The unique ID of the alumni
     * @type {string}
     * @memberof AlumniOptionDto
     */
    id: string;
    /**
     * The name of the alumni
     * @type {string}
     * @memberof AlumniOptionDto
     */
    fullName: string;
}

/**
 * Check if a given object implements the AlumniOptionDto interface.
 */
export function instanceOfAlumniOptionDto(value: object): value is AlumniOptionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    return true;
}

export function AlumniOptionDtoFromJSON(json: any): AlumniOptionDto {
    return AlumniOptionDtoFromJSONTyped(json, false);
}

export function AlumniOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlumniOptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'fullName': json['fullName'],
    };
}

export function AlumniOptionDtoToJSON(json: any): AlumniOptionDto {
    return AlumniOptionDtoToJSONTyped(json, false);
}

export function AlumniOptionDtoToJSONTyped(value?: AlumniOptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fullName': value['fullName'],
    };
}

