/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtendedCompanyDto } from './ExtendedCompanyDto';
import {
    ExtendedCompanyDtoFromJSON,
    ExtendedCompanyDtoFromJSONTyped,
    ExtendedCompanyDtoToJSON,
    ExtendedCompanyDtoToJSONTyped,
} from './ExtendedCompanyDto';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface AlumniPastLocationsAndCompaniesDto
 */
export interface AlumniPastLocationsAndCompaniesDto {
    /**
     * The Company of the review
     * @type {Array<ExtendedCompanyDto>}
     * @memberof AlumniPastLocationsAndCompaniesDto
     */
    companies?: Array<ExtendedCompanyDto>;
    /**
     * The Location of the review
     * @type {Array<Location>}
     * @memberof AlumniPastLocationsAndCompaniesDto
     */
    locations?: Array<Location>;
}

/**
 * Check if a given object implements the AlumniPastLocationsAndCompaniesDto interface.
 */
export function instanceOfAlumniPastLocationsAndCompaniesDto(value: object): value is AlumniPastLocationsAndCompaniesDto {
    return true;
}

export function AlumniPastLocationsAndCompaniesDtoFromJSON(json: any): AlumniPastLocationsAndCompaniesDto {
    return AlumniPastLocationsAndCompaniesDtoFromJSONTyped(json, false);
}

export function AlumniPastLocationsAndCompaniesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlumniPastLocationsAndCompaniesDto {
    if (json == null) {
        return json;
    }
    return {
        
        'companies': json['Companies'] == null ? undefined : ((json['Companies'] as Array<any>).map(ExtendedCompanyDtoFromJSON)),
        'locations': json['Locations'] == null ? undefined : ((json['Locations'] as Array<any>).map(LocationFromJSON)),
    };
}

export function AlumniPastLocationsAndCompaniesDtoToJSON(json: any): AlumniPastLocationsAndCompaniesDto {
    return AlumniPastLocationsAndCompaniesDtoToJSONTyped(json, false);
}

export function AlumniPastLocationsAndCompaniesDtoToJSONTyped(value?: AlumniPastLocationsAndCompaniesDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Companies': value['companies'] == null ? undefined : ((value['companies'] as Array<any>).map(ExtendedCompanyDtoToJSON)),
        'Locations': value['locations'] == null ? undefined : ((value['locations'] as Array<any>).map(LocationToJSON)),
    };
}

