/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlumniListItemDto } from './AlumniListItemDto';
import {
    AlumniListItemDtoFromJSON,
    AlumniListItemDtoFromJSONTyped,
    AlumniListItemDtoToJSON,
    AlumniListItemDtoToJSONTyped,
} from './AlumniListItemDto';

/**
 * 
 * @export
 * @interface AlumniListResponseDto
 */
export interface AlumniListResponseDto {
    /**
     * 
     * @type {Array<AlumniListItemDto>}
     * @memberof AlumniListResponseDto
     */
    alumni: Array<AlumniListItemDto>;
    /**
     * The total number of alumni in the database before applying the filters
     * @type {number}
     * @memberof AlumniListResponseDto
     */
    count: number;
    /**
     * The total number of alumni in the database after applying the filters
     * @type {number}
     * @memberof AlumniListResponseDto
     */
    filteredCount: number;
}

/**
 * Check if a given object implements the AlumniListResponseDto interface.
 */
export function instanceOfAlumniListResponseDto(value: object): value is AlumniListResponseDto {
    if (!('alumni' in value) || value['alumni'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('filteredCount' in value) || value['filteredCount'] === undefined) return false;
    return true;
}

export function AlumniListResponseDtoFromJSON(json: any): AlumniListResponseDto {
    return AlumniListResponseDtoFromJSONTyped(json, false);
}

export function AlumniListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlumniListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'alumni': ((json['alumni'] as Array<any>).map(AlumniListItemDtoFromJSON)),
        'count': json['count'],
        'filteredCount': json['filteredCount'],
    };
}

export function AlumniListResponseDtoToJSON(json: any): AlumniListResponseDto {
    return AlumniListResponseDtoToJSONTyped(json, false);
}

export function AlumniListResponseDtoToJSONTyped(value?: AlumniListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alumni': ((value['alumni'] as Array<any>).map(AlumniListItemDtoToJSON)),
        'count': value['count'],
        'filteredCount': value['filteredCount'],
    };
}

