/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasicGeoDto
 */
export interface BasicGeoDto {
    /**
     * The country name
     * @type {string}
     * @memberof BasicGeoDto
     */
    country: string;
    /**
     * The code of the country
     * @type {string}
     * @memberof BasicGeoDto
     */
    code: string;
    /**
     * The number of alumni in the country
     * @type {number}
     * @memberof BasicGeoDto
     */
    count: number;
}

/**
 * Check if a given object implements the BasicGeoDto interface.
 */
export function instanceOfBasicGeoDto(value: object): value is BasicGeoDto {
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function BasicGeoDtoFromJSON(json: any): BasicGeoDto {
    return BasicGeoDtoFromJSONTyped(json, false);
}

export function BasicGeoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicGeoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'],
        'code': json['code'],
        'count': json['count'],
    };
}

export function BasicGeoDtoToJSON(json: any): BasicGeoDto {
    return BasicGeoDtoToJSONTyped(json, false);
}

export function BasicGeoDtoToJSONTyped(value?: BasicGeoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'code': value['code'],
        'count': value['count'],
    };
}

