/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeReviewScoreDto
 */
export interface ChangeReviewScoreDto {
    /**
     * The id of the alumni
     * @type {string}
     * @memberof ChangeReviewScoreDto
     */
    alumniId: string;
    /**
     * The id of the review
     * @type {string}
     * @memberof ChangeReviewScoreDto
     */
    reviewId: string;
    /**
     * The review rating
     * @type {boolean}
     * @memberof ChangeReviewScoreDto
     */
    upvote: boolean;
}

/**
 * Check if a given object implements the ChangeReviewScoreDto interface.
 */
export function instanceOfChangeReviewScoreDto(value: object): value is ChangeReviewScoreDto {
    if (!('alumniId' in value) || value['alumniId'] === undefined) return false;
    if (!('reviewId' in value) || value['reviewId'] === undefined) return false;
    if (!('upvote' in value) || value['upvote'] === undefined) return false;
    return true;
}

export function ChangeReviewScoreDtoFromJSON(json: any): ChangeReviewScoreDto {
    return ChangeReviewScoreDtoFromJSONTyped(json, false);
}

export function ChangeReviewScoreDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeReviewScoreDto {
    if (json == null) {
        return json;
    }
    return {
        
        'alumniId': json['alumniId'],
        'reviewId': json['reviewId'],
        'upvote': json['upvote'],
    };
}

export function ChangeReviewScoreDtoToJSON(json: any): ChangeReviewScoreDto {
    return ChangeReviewScoreDtoToJSONTyped(json, false);
}

export function ChangeReviewScoreDtoToJSONTyped(value?: ChangeReviewScoreDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alumniId': value['alumniId'],
        'reviewId': value['reviewId'],
        'upvote': value['upvote'],
    };
}

