/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataPointDto } from './DataPointDto';
import {
    DataPointDtoFromJSON,
    DataPointDtoFromJSONTyped,
    DataPointDtoToJSON,
    DataPointDtoToJSONTyped,
} from './DataPointDto';

/**
 * 
 * @export
 * @interface CityListItemDto
 */
export interface CityListItemDto {
    /**
     * The city ID
     * @type {string}
     * @memberof CityListItemDto
     */
    id: string;
    /**
     * The city name
     * @type {string}
     * @memberof CityListItemDto
     */
    name: string;
    /**
     * The country code of the country that the city belongs to
     * @type {string}
     * @memberof CityListItemDto
     */
    code: string;
    /**
     * The latitude of the city
     * @type {number}
     * @memberof CityListItemDto
     */
    latitude?: number;
    /**
     * The longitude of the city
     * @type {number}
     * @memberof CityListItemDto
     */
    longitude: number;
    /**
     * The number of alumni in the city
     * @type {number}
     * @memberof CityListItemDto
     */
    count: number;
    /**
     * The alumni count trend of the city
     * @type {Array<DataPointDto>}
     * @memberof CityListItemDto
     */
    trend: Array<DataPointDto>;
}

/**
 * Check if a given object implements the CityListItemDto interface.
 */
export function instanceOfCityListItemDto(value: object): value is CityListItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('trend' in value) || value['trend'] === undefined) return false;
    return true;
}

export function CityListItemDtoFromJSON(json: any): CityListItemDto {
    return CityListItemDtoFromJSONTyped(json, false);
}

export function CityListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'],
        'count': json['count'],
        'trend': ((json['trend'] as Array<any>).map(DataPointDtoFromJSON)),
    };
}

export function CityListItemDtoToJSON(json: any): CityListItemDto {
    return CityListItemDtoToJSONTyped(json, false);
}

export function CityListItemDtoToJSONTyped(value?: CityListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'count': value['count'],
        'trend': ((value['trend'] as Array<any>).map(DataPointDtoToJSON)),
    };
}

