/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityListItemDto
 */
export interface CityListItemDto {
    /**
     * The city ID
     * @type {string}
     * @memberof CityListItemDto
     */
    id: string;
    /**
     * The city name
     * @type {string}
     * @memberof CityListItemDto
     */
    name: string;
    /**
     * The country code of the country that the city belongs to
     * @type {string}
     * @memberof CityListItemDto
     */
    code: string;
    /**
     * The number of alumni in the city
     * @type {number}
     * @memberof CityListItemDto
     */
    alumniCount: number;
    /**
     * The number of companies in the city
     * @type {number}
     * @memberof CityListItemDto
     */
    companyCount: number;
}

/**
 * Check if a given object implements the CityListItemDto interface.
 */
export function instanceOfCityListItemDto(value: object): value is CityListItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('alumniCount' in value) || value['alumniCount'] === undefined) return false;
    if (!('companyCount' in value) || value['companyCount'] === undefined) return false;
    return true;
}

export function CityListItemDtoFromJSON(json: any): CityListItemDto {
    return CityListItemDtoFromJSONTyped(json, false);
}

export function CityListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'alumniCount': json['alumniCount'],
        'companyCount': json['companyCount'],
    };
}

export function CityListItemDtoToJSON(json: any): CityListItemDto {
    return CityListItemDtoToJSONTyped(json, false);
}

export function CityListItemDtoToJSONTyped(value?: CityListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'alumniCount': value['alumniCount'],
        'companyCount': value['companyCount'],
    };
}

