/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityOptionDto
 */
export interface CityOptionDto {
    /**
     * The unique ID of the city
     * @type {string}
     * @memberof CityOptionDto
     */
    id: string;
    /**
     * The name of the city
     * @type {string}
     * @memberof CityOptionDto
     */
    name: string;
    /**
     * The country of the city
     * @type {string}
     * @memberof CityOptionDto
     */
    country: string;
}

/**
 * Check if a given object implements the CityOptionDto interface.
 */
export function instanceOfCityOptionDto(value: object): value is CityOptionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function CityOptionDtoFromJSON(json: any): CityOptionDto {
    return CityOptionDtoFromJSONTyped(json, false);
}

export function CityOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityOptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'country': json['country'],
    };
}

export function CityOptionDtoToJSON(json: any): CityOptionDto {
    return CityOptionDtoToJSONTyped(json, false);
}

export function CityOptionDtoToJSONTyped(value?: CityOptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'country': value['country'],
    };
}

