/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The size of the company
 * @export
 */
export const COMPANYSIZE = {
    NotSpecified: 'Not specified',
    _110Employees: '1-10 employees',
    _1150Employees: '11-50 employees',
    _51200Employees: '51-200 employees',
    _201500Employees: '201-500 employees',
    _5011000Employees: '501-1000 employees',
    _10015000Employees: '1,001-5,000 employees',
    _500110000Employees: '5,001-10,000 employees',
    _10001Employees: '10,001+ employees'
} as const;
export type COMPANYSIZE = typeof COMPANYSIZE[keyof typeof COMPANYSIZE];


export function instanceOfCOMPANYSIZE(value: any): boolean {
    for (const key in COMPANYSIZE) {
        if (Object.prototype.hasOwnProperty.call(COMPANYSIZE, key)) {
            if (COMPANYSIZE[key as keyof typeof COMPANYSIZE] === value) {
                return true;
            }
        }
    }
    return false;
}

export function COMPANYSIZEFromJSON(json: any): COMPANYSIZE {
    return COMPANYSIZEFromJSONTyped(json, false);
}

export function COMPANYSIZEFromJSONTyped(json: any, ignoreDiscriminator: boolean): COMPANYSIZE {
    return json as COMPANYSIZE;
}

export function COMPANYSIZEToJSON(value?: COMPANYSIZE | null): any {
    return value as any;
}

export function COMPANYSIZEToJSONTyped(value: any, ignoreDiscriminator: boolean): COMPANYSIZE {
    return value as COMPANYSIZE;
}

