/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataPointDto } from './DataPointDto';
import {
    DataPointDtoFromJSON,
    DataPointDtoFromJSONTyped,
    DataPointDtoToJSON,
    DataPointDtoToJSONTyped,
} from './DataPointDto';

/**
 * 
 * @export
 * @interface CompanyListItemDto
 */
export interface CompanyListItemDto {
    /**
     * The ID of the company
     * @type {string}
     * @memberof CompanyListItemDto
     */
    id: string;
    /**
     * The name of the company
     * @type {string}
     * @memberof CompanyListItemDto
     */
    name: string;
    /**
     * The number of alumni in the company
     * @type {number}
     * @memberof CompanyListItemDto
     */
    count: number;
    /**
     * The trend of the company
     * @type {Array<DataPointDto>}
     * @memberof CompanyListItemDto
     */
    trend: Array<DataPointDto>;
    /**
     * 
     * @type {string}
     * @memberof CompanyListItemDto
     */
    logo?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyListItemDto
     */
    levelsFyiUrl?: string;
}

/**
 * Check if a given object implements the CompanyListItemDto interface.
 */
export function instanceOfCompanyListItemDto(value: object): value is CompanyListItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('trend' in value) || value['trend'] === undefined) return false;
    return true;
}

export function CompanyListItemDtoFromJSON(json: any): CompanyListItemDto {
    return CompanyListItemDtoFromJSONTyped(json, false);
}

export function CompanyListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'count': json['count'],
        'trend': ((json['trend'] as Array<any>).map(DataPointDtoFromJSON)),
        'logo': json['logo'] == null ? undefined : json['logo'],
        'levelsFyiUrl': json['levelsFyiUrl'] == null ? undefined : json['levelsFyiUrl'],
    };
}

export function CompanyListItemDtoToJSON(json: any): CompanyListItemDto {
    return CompanyListItemDtoToJSONTyped(json, false);
}

export function CompanyListItemDtoToJSONTyped(value?: CompanyListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'count': value['count'],
        'trend': ((value['trend'] as Array<any>).map(DataPointDtoToJSON)),
        'logo': value['logo'],
        'levelsFyiUrl': value['levelsFyiUrl'],
    };
}

