/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountryListItemDto
 */
export interface CountryListItemDto {
    /**
     * The country ID
     * @type {string}
     * @memberof CountryListItemDto
     */
    id: string;
    /**
     * The country name
     * @type {string}
     * @memberof CountryListItemDto
     */
    name: string;
    /**
     * The country code (ISO 3166-1 alpha-2)
     * @type {string}
     * @memberof CountryListItemDto
     */
    code: string;
    /**
     * The number of alumni in the country
     * @type {number}
     * @memberof CountryListItemDto
     */
    alumniCount: number;
    /**
     * The number of companies in the country
     * @type {number}
     * @memberof CountryListItemDto
     */
    companyCount: number;
}

/**
 * Check if a given object implements the CountryListItemDto interface.
 */
export function instanceOfCountryListItemDto(value: object): value is CountryListItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('alumniCount' in value) || value['alumniCount'] === undefined) return false;
    if (!('companyCount' in value) || value['companyCount'] === undefined) return false;
    return true;
}

export function CountryListItemDtoFromJSON(json: any): CountryListItemDto {
    return CountryListItemDtoFromJSONTyped(json, false);
}

export function CountryListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'code': json['code'],
        'alumniCount': json['alumniCount'],
        'companyCount': json['companyCount'],
    };
}

export function CountryListItemDtoToJSON(json: any): CountryListItemDto {
    return CountryListItemDtoToJSONTyped(json, false);
}

export function CountryListItemDtoToJSONTyped(value?: CountryListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'alumniCount': value['alumniCount'],
        'companyCount': value['companyCount'],
    };
}

