/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CourseCompletion
 */
export interface CourseCompletion {
    /**
     * The ID of the course
     * @type {string}
     * @memberof CourseCompletion
     */
    courseId: string;
    /**
     * The year of conclusion of the course
     * @type {number}
     * @memberof CourseCompletion
     */
    conclusionYear: number;
}

/**
 * Check if a given object implements the CourseCompletion interface.
 */
export function instanceOfCourseCompletion(value: object): value is CourseCompletion {
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('conclusionYear' in value) || value['conclusionYear'] === undefined) return false;
    return true;
}

export function CourseCompletionFromJSON(json: any): CourseCompletion {
    return CourseCompletionFromJSONTyped(json, false);
}

export function CourseCompletionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CourseCompletion {
    if (json == null) {
        return json;
    }
    return {
        
        'courseId': json['courseId'],
        'conclusionYear': json['conclusionYear'],
    };
}

export function CourseCompletionToJSON(json: any): CourseCompletion {
    return CourseCompletionToJSONTyped(json, false);
}

export function CourseCompletionToJSONTyped(value?: CourseCompletion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseId': value['courseId'],
        'conclusionYear': value['conclusionYear'],
    };
}

