/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUserDto
 */
export interface DeleteUserDto {
    /**
     * The id of the user to delete
     * @type {string}
     * @memberof DeleteUserDto
     */
    id: string;
}

/**
 * Check if a given object implements the DeleteUserDto interface.
 */
export function instanceOfDeleteUserDto(value: object): value is DeleteUserDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DeleteUserDtoFromJSON(json: any): DeleteUserDto {
    return DeleteUserDtoFromJSONTyped(json, false);
}

export function DeleteUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteUserDtoToJSON(json: any): DeleteUserDto {
    return DeleteUserDtoToJSONTyped(json, false);
}

export function DeleteUserDtoToJSONTyped(value?: DeleteUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

