/* tslint:disable */
/* eslint-disable */
/**
 * Alumni Feup API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EducationListItemDto } from './EducationListItemDto';
import {
    EducationListItemDtoFromJSON,
    EducationListItemDtoFromJSONTyped,
    EducationListItemDtoToJSON,
    EducationListItemDtoToJSONTyped,
} from './EducationListItemDto';

/**
 * 
 * @export
 * @interface EducationListResponseDto
 */
export interface EducationListResponseDto {
    /**
     * 
     * @type {Array<EducationListItemDto>}
     * @memberof EducationListResponseDto
     */
    education: Array<EducationListItemDto>;
    /**
     * 
     * @type {number}
     * @memberof EducationListResponseDto
     */
    count: number;
}

/**
 * Check if a given object implements the EducationListResponseDto interface.
 */
export function instanceOfEducationListResponseDto(value: object): value is EducationListResponseDto {
    if (!('education' in value) || value['education'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function EducationListResponseDtoFromJSON(json: any): EducationListResponseDto {
    return EducationListResponseDtoFromJSONTyped(json, false);
}

export function EducationListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'education': ((json['education'] as Array<any>).map(EducationListItemDtoFromJSON)),
        'count': json['count'],
    };
}

export function EducationListResponseDtoToJSON(json: any): EducationListResponseDto {
    return EducationListResponseDtoToJSONTyped(json, false);
}

export function EducationListResponseDtoToJSONTyped(value?: EducationListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'education': ((value['education'] as Array<any>).map(EducationListItemDtoToJSON)),
        'count': value['count'],
    };
}

