/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluateSeniorityLevelDto
 */
export interface EvaluateSeniorityLevelDto {
    /**
     * Whether the seniority level was accepted by the user
     * @type {boolean}
     * @memberof EvaluateSeniorityLevelDto
     */
    wasSeniorityLevelAcceptedByUser: boolean;
}

/**
 * Check if a given object implements the EvaluateSeniorityLevelDto interface.
 */
export function instanceOfEvaluateSeniorityLevelDto(value: object): value is EvaluateSeniorityLevelDto {
    if (!('wasSeniorityLevelAcceptedByUser' in value) || value['wasSeniorityLevelAcceptedByUser'] === undefined) return false;
    return true;
}

export function EvaluateSeniorityLevelDtoFromJSON(json: any): EvaluateSeniorityLevelDto {
    return EvaluateSeniorityLevelDtoFromJSONTyped(json, false);
}

export function EvaluateSeniorityLevelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluateSeniorityLevelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'wasSeniorityLevelAcceptedByUser': json['wasSeniorityLevelAcceptedByUser'],
    };
}

export function EvaluateSeniorityLevelDtoToJSON(json: any): EvaluateSeniorityLevelDto {
    return EvaluateSeniorityLevelDtoToJSONTyped(json, false);
}

export function EvaluateSeniorityLevelDtoToJSONTyped(value?: EvaluateSeniorityLevelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wasSeniorityLevelAcceptedByUser': value['wasSeniorityLevelAcceptedByUser'],
    };
}

