/* tslint:disable */
/* eslint-disable */
/**
 * Alumni Feup API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluateClassificationDto
 */
export interface EvaluateClassificationDto {
    /**
     * Whether the job classification was accepted by the user
     * @type {boolean}
     * @memberof EvaluateClassificationDto
     */
    wasAcceptedByUser: boolean;
}

/**
 * Check if a given object implements the EvaluateClassificationDto interface.
 */
export function instanceOfEvaluateClassificationDto(value: object): value is EvaluateClassificationDto {
    if (!('wasAcceptedByUser' in value) || value['wasAcceptedByUser'] === undefined) return false;
    return true;
}

export function EvaluateClassificationDtoFromJSON(json: any): EvaluateClassificationDto {
    return EvaluateClassificationDtoFromJSONTyped(json, false);
}

export function EvaluateClassificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluateClassificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'wasAcceptedByUser': json['wasAcceptedByUser'],
    };
}

export function EvaluateClassificationDtoToJSON(json: any): EvaluateClassificationDto {
    return EvaluateClassificationDtoToJSONTyped(json, false);
}

export function EvaluateClassificationDtoToJSONTyped(value?: EvaluateClassificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wasAcceptedByUser': value['wasAcceptedByUser'],
    };
}

