/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface ExtendedCompanyDto
 */
export interface ExtendedCompanyDto {
    /**
     * 
     * @type {string}
     * @memberof ExtendedCompanyDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCompanyDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCompanyDto
     */
    industry: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCompanyDto
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCompanyDto
     */
    linkedinUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ExtendedCompanyDto
     */
    logo?: string;
    /**
     * The current location of the alumni
     * @type {Location}
     * @memberof ExtendedCompanyDto
     */
    location?: Location;
}

/**
 * Check if a given object implements the ExtendedCompanyDto interface.
 */
export function instanceOfExtendedCompanyDto(value: object): value is ExtendedCompanyDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('industry' in value) || value['industry'] === undefined) return false;
    return true;
}

export function ExtendedCompanyDtoFromJSON(json: any): ExtendedCompanyDto {
    return ExtendedCompanyDtoFromJSONTyped(json, false);
}

export function ExtendedCompanyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedCompanyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'industry': json['industry'],
        'website': json['website'] == null ? undefined : json['website'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
    };
}

export function ExtendedCompanyDtoToJSON(json: any): ExtendedCompanyDto {
    return ExtendedCompanyDtoToJSONTyped(json, false);
}

export function ExtendedCompanyDtoToJSONTyped(value?: ExtendedCompanyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'industry': value['industry'],
        'website': value['website'],
        'linkedinUrl': value['linkedinUrl'],
        'logo': value['logo'],
        'location': LocationToJSON(value['location']),
    };
}

