/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FacultyListItemDto } from './FacultyListItemDto';
import {
    FacultyListItemDtoFromJSON,
    FacultyListItemDtoFromJSONTyped,
    FacultyListItemDtoToJSON,
    FacultyListItemDtoToJSONTyped,
} from './FacultyListItemDto';

/**
 * 
 * @export
 * @interface FacultyListDto
 */
export interface FacultyListDto {
    /**
     * The faculty list
     * @type {Array<FacultyListItemDto>}
     * @memberof FacultyListDto
     */
    faculties: Array<FacultyListItemDto>;
    /**
     * The number of faculties, after applying the filters
     * @type {number}
     * @memberof FacultyListDto
     */
    filteredCount: number;
    /**
     * The total number of faculties, regardless of filters
     * @type {number}
     * @memberof FacultyListDto
     */
    count: number;
}

/**
 * Check if a given object implements the FacultyListDto interface.
 */
export function instanceOfFacultyListDto(value: object): value is FacultyListDto {
    if (!('faculties' in value) || value['faculties'] === undefined) return false;
    if (!('filteredCount' in value) || value['filteredCount'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function FacultyListDtoFromJSON(json: any): FacultyListDto {
    return FacultyListDtoFromJSONTyped(json, false);
}

export function FacultyListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacultyListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'faculties': ((json['faculties'] as Array<any>).map(FacultyListItemDtoFromJSON)),
        'filteredCount': json['filteredCount'],
        'count': json['count'],
    };
}

export function FacultyListDtoToJSON(json: any): FacultyListDto {
    return FacultyListDtoToJSONTyped(json, false);
}

export function FacultyListDtoToJSONTyped(value?: FacultyListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'faculties': ((value['faculties'] as Array<any>).map(FacultyListItemDtoToJSON)),
        'filteredCount': value['filteredCount'],
        'count': value['count'],
    };
}

