/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataPointDto } from './DataPointDto';
import {
    DataPointDtoFromJSON,
    DataPointDtoFromJSONTyped,
    DataPointDtoToJSON,
    DataPointDtoToJSONTyped,
} from './DataPointDto';

/**
 * 
 * @export
 * @interface FacultyListItemDto
 */
export interface FacultyListItemDto {
    /**
     * The faculty ID
     * @type {string}
     * @memberof FacultyListItemDto
     */
    id: string;
    /**
     * The faculty name
     * @type {string}
     * @memberof FacultyListItemDto
     */
    name: string;
    /**
     * The faculty acronym
     * @type {string}
     * @memberof FacultyListItemDto
     */
    acronym: string;
    /**
     * The graduations trend of the faculty
     * @type {Array<DataPointDto>}
     * @memberof FacultyListItemDto
     */
    trend: Array<DataPointDto>;
    /**
     * The number of alumni that graduated from the faculty
     * @type {number}
     * @memberof FacultyListItemDto
     */
    count: number;
}

/**
 * Check if a given object implements the FacultyListItemDto interface.
 */
export function instanceOfFacultyListItemDto(value: object): value is FacultyListItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('acronym' in value) || value['acronym'] === undefined) return false;
    if (!('trend' in value) || value['trend'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function FacultyListItemDtoFromJSON(json: any): FacultyListItemDto {
    return FacultyListItemDtoFromJSONTyped(json, false);
}

export function FacultyListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacultyListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'acronym': json['acronym'],
        'trend': ((json['trend'] as Array<any>).map(DataPointDtoFromJSON)),
        'count': json['count'],
    };
}

export function FacultyListItemDtoToJSON(json: any): FacultyListItemDto {
    return FacultyListItemDtoToJSONTyped(json, false);
}

export function FacultyListItemDtoToJSONTyped(value?: FacultyListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'acronym': value['acronym'],
        'trend': ((value['trend'] as Array<any>).map(DataPointDtoToJSON)),
        'count': value['count'],
    };
}

