/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoJSONFeature
 */
export interface GeoJSONFeature {
    /**
     * 
     * @type {string}
     * @memberof GeoJSONFeature
     */
    type: string;
    /**
     * 
     * @type {object}
     * @memberof GeoJSONFeature
     */
    geometry: object;
    /**
     * 
     * @type {object}
     * @memberof GeoJSONFeature
     */
    properties: object;
}

/**
 * Check if a given object implements the GeoJSONFeature interface.
 */
export function instanceOfGeoJSONFeature(value: object): value is GeoJSONFeature {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('geometry' in value) || value['geometry'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function GeoJSONFeatureFromJSON(json: any): GeoJSONFeature {
    return GeoJSONFeatureFromJSONTyped(json, false);
}

export function GeoJSONFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJSONFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'geometry': json['geometry'],
        'properties': json['properties'],
    };
}

export function GeoJSONFeatureToJSON(json: any): GeoJSONFeature {
    return GeoJSONFeatureToJSONTyped(json, false);
}

export function GeoJSONFeatureToJSONTyped(value?: GeoJSONFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'geometry': value['geometry'],
        'properties': value['properties'],
    };
}

