/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraduationListItemDto
 */
export interface GraduationListItemDto {
    /**
     * The course ID
     * @type {string}
     * @memberof GraduationListItemDto
     */
    id: string;
    /**
     * For viz purposes
     * @type {string}
     * @memberof GraduationListItemDto
     */
    name: string;
    /**
     * The year of graduation
     * @type {number}
     * @memberof GraduationListItemDto
     */
    year: number;
    /**
     * The major acronym
     * @type {string}
     * @memberof GraduationListItemDto
     */
    acronym: string;
    /**
     * The number of alumni that graduated from the major in the year
     * @type {number}
     * @memberof GraduationListItemDto
     */
    count: number;
}

/**
 * Check if a given object implements the GraduationListItemDto interface.
 */
export function instanceOfGraduationListItemDto(value: object): value is GraduationListItemDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    if (!('acronym' in value) || value['acronym'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function GraduationListItemDtoFromJSON(json: any): GraduationListItemDto {
    return GraduationListItemDtoFromJSONTyped(json, false);
}

export function GraduationListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraduationListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'year': json['year'],
        'acronym': json['acronym'],
        'count': json['count'],
    };
}

export function GraduationListItemDtoToJSON(json: any): GraduationListItemDto {
    return GraduationListItemDtoToJSONTyped(json, false);
}

export function GraduationListItemDtoToJSONTyped(value?: GraduationListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'year': value['year'],
        'acronym': value['acronym'],
        'count': value['count'],
    };
}

