/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CourseAnalyticsEntity } from './CourseAnalyticsEntity';
import {
    CourseAnalyticsEntityFromJSON,
    CourseAnalyticsEntityFromJSONTyped,
    CourseAnalyticsEntityToJSON,
    CourseAnalyticsEntityToJSONTyped,
} from './CourseAnalyticsEntity';

/**
 * 
 * @export
 * @interface GraduationAnalyticsEntity
 */
export interface GraduationAnalyticsEntity {
    /**
     * The id of the graduation
     * @type {string}
     * @memberof GraduationAnalyticsEntity
     */
    id: string;
    /**
     * The id of the alumni
     * @type {string}
     * @memberof GraduationAnalyticsEntity
     */
    alumniId: string;
    /**
     * The id of the course
     * @type {string}
     * @memberof GraduationAnalyticsEntity
     */
    courseId: string;
    /**
     * The year of graduation
     * @type {number}
     * @memberof GraduationAnalyticsEntity
     */
    conclusionYear: number;
    /**
     * The course of the graduation
     * @type {CourseAnalyticsEntity}
     * @memberof GraduationAnalyticsEntity
     */
    course: CourseAnalyticsEntity;
}

/**
 * Check if a given object implements the GraduationAnalyticsEntity interface.
 */
export function instanceOfGraduationAnalyticsEntity(value: object): value is GraduationAnalyticsEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('alumniId' in value) || value['alumniId'] === undefined) return false;
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('conclusionYear' in value) || value['conclusionYear'] === undefined) return false;
    if (!('course' in value) || value['course'] === undefined) return false;
    return true;
}

export function GraduationAnalyticsEntityFromJSON(json: any): GraduationAnalyticsEntity {
    return GraduationAnalyticsEntityFromJSONTyped(json, false);
}

export function GraduationAnalyticsEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraduationAnalyticsEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'alumniId': json['alumniId'],
        'courseId': json['courseId'],
        'conclusionYear': json['conclusionYear'],
        'course': CourseAnalyticsEntityFromJSON(json['course']),
    };
}

export function GraduationAnalyticsEntityToJSON(json: any): GraduationAnalyticsEntity {
    return GraduationAnalyticsEntityToJSONTyped(json, false);
}

export function GraduationAnalyticsEntityToJSONTyped(value?: GraduationAnalyticsEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'alumniId': value['alumniId'],
        'courseId': value['courseId'],
        'conclusionYear': value['conclusionYear'],
        'course': CourseAnalyticsEntityToJSON(value['course']),
    };
}

