/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IndustryListItemDto } from './IndustryListItemDto';
import {
    IndustryListItemDtoFromJSON,
    IndustryListItemDtoFromJSONTyped,
    IndustryListItemDtoToJSON,
    IndustryListItemDtoToJSONTyped,
} from './IndustryListItemDto';

/**
 * 
 * @export
 * @interface IndustryListResponseDto
 */
export interface IndustryListResponseDto {
    /**
     * 
     * @type {Array<IndustryListItemDto>}
     * @memberof IndustryListResponseDto
     */
    industries: Array<IndustryListItemDto>;
    /**
     * The total number of industries in the database
     * @type {number}
     * @memberof IndustryListResponseDto
     */
    count: number;
    /**
     * The total number of industries in the database before applying the filters
     * @type {number}
     * @memberof IndustryListResponseDto
     */
    filteredCount: number;
}

/**
 * Check if a given object implements the IndustryListResponseDto interface.
 */
export function instanceOfIndustryListResponseDto(value: object): value is IndustryListResponseDto {
    if (!('industries' in value) || value['industries'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('filteredCount' in value) || value['filteredCount'] === undefined) return false;
    return true;
}

export function IndustryListResponseDtoFromJSON(json: any): IndustryListResponseDto {
    return IndustryListResponseDtoFromJSONTyped(json, false);
}

export function IndustryListResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndustryListResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'industries': ((json['industries'] as Array<any>).map(IndustryListItemDtoFromJSON)),
        'count': json['count'],
        'filteredCount': json['filteredCount'],
    };
}

export function IndustryListResponseDtoToJSON(json: any): IndustryListResponseDto {
    return IndustryListResponseDtoToJSONTyped(json, false);
}

export function IndustryListResponseDtoToJSONTyped(value?: IndustryListResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'industries': ((value['industries'] as Array<any>).map(IndustryListItemDtoToJSON)),
        'count': value['count'],
        'filteredCount': value['filteredCount'],
    };
}

