/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteUserDto
 */
export interface InviteUserDto {
    /**
     * The email of the user to invite
     * @type {string}
     * @memberof InviteUserDto
     */
    email: string;
}

/**
 * Check if a given object implements the InviteUserDto interface.
 */
export function instanceOfInviteUserDto(value: object): value is InviteUserDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function InviteUserDtoFromJSON(json: any): InviteUserDto {
    return InviteUserDtoFromJSONTyped(json, false);
}

export function InviteUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function InviteUserDtoToJSON(json: any): InviteUserDto {
    return InviteUserDtoToJSONTyped(json, false);
}

export function InviteUserDtoToJSONTyped(value?: InviteUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

