/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EscoClassificationAnalyticsEntity } from './EscoClassificationAnalyticsEntity';
import {
    EscoClassificationAnalyticsEntityFromJSON,
    EscoClassificationAnalyticsEntityFromJSONTyped,
    EscoClassificationAnalyticsEntityToJSON,
    EscoClassificationAnalyticsEntityToJSONTyped,
} from './EscoClassificationAnalyticsEntity';

/**
 * 
 * @export
 * @interface JobClassificationAnalyticsEntity
 */
export interface JobClassificationAnalyticsEntity {
    /**
     * 
     * @type {string}
     * @memberof JobClassificationAnalyticsEntity
     */
    escoClassificationId: string;
    /**
     * 
     * @type {string}
     * @memberof JobClassificationAnalyticsEntity
     */
    roleId: string;
    /**
     * The confidence of the job classification
     * @type {number}
     * @memberof JobClassificationAnalyticsEntity
     */
    confidence?: number;
    /**
     * 
     * @type {EscoClassificationAnalyticsEntity}
     * @memberof JobClassificationAnalyticsEntity
     */
    escoClassification: EscoClassificationAnalyticsEntity;
}

/**
 * Check if a given object implements the JobClassificationAnalyticsEntity interface.
 */
export function instanceOfJobClassificationAnalyticsEntity(value: object): value is JobClassificationAnalyticsEntity {
    if (!('escoClassificationId' in value) || value['escoClassificationId'] === undefined) return false;
    if (!('roleId' in value) || value['roleId'] === undefined) return false;
    if (!('escoClassification' in value) || value['escoClassification'] === undefined) return false;
    return true;
}

export function JobClassificationAnalyticsEntityFromJSON(json: any): JobClassificationAnalyticsEntity {
    return JobClassificationAnalyticsEntityFromJSONTyped(json, false);
}

export function JobClassificationAnalyticsEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobClassificationAnalyticsEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'escoClassificationId': json['escoClassificationId'],
        'roleId': json['roleId'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'escoClassification': EscoClassificationAnalyticsEntityFromJSON(json['escoClassification']),
    };
}

export function JobClassificationAnalyticsEntityToJSON(json: any): JobClassificationAnalyticsEntity {
    return JobClassificationAnalyticsEntityToJSONTyped(json, false);
}

export function JobClassificationAnalyticsEntityToJSONTyped(value?: JobClassificationAnalyticsEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'escoClassificationId': value['escoClassificationId'],
        'roleId': value['roleId'],
        'confidence': value['confidence'],
        'escoClassification': EscoClassificationAnalyticsEntityToJSON(value['escoClassification']),
    };
}

