/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobClassificationChoiceVo
 */
export interface JobClassificationChoiceVo {
    /**
     * The id of the choice
     * @type {string}
     * @memberof JobClassificationChoiceVo
     */
    id?: string;
    /**
     * The title of the choice
     * @type {string}
     * @memberof JobClassificationChoiceVo
     */
    title?: string;
    /**
     * The confidence of the choice
     * @type {number}
     * @memberof JobClassificationChoiceVo
     */
    confidence?: number;
}

/**
 * Check if a given object implements the JobClassificationChoiceVo interface.
 */
export function instanceOfJobClassificationChoiceVo(value: object): value is JobClassificationChoiceVo {
    return true;
}

export function JobClassificationChoiceVoFromJSON(json: any): JobClassificationChoiceVo {
    return JobClassificationChoiceVoFromJSONTyped(json, false);
}

export function JobClassificationChoiceVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobClassificationChoiceVo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
    };
}

export function JobClassificationChoiceVoToJSON(json: any): JobClassificationChoiceVo {
    return JobClassificationChoiceVoToJSONTyped(json, false);
}

export function JobClassificationChoiceVoToJSONTyped(value?: JobClassificationChoiceVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'confidence': value['confidence'],
    };
}

