/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkedinAuthDto
 */
export interface LinkedinAuthDto {
    /**
     * A unique identifying value for the member. Referenced as personId in other API documentation pages.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    personId: string;
    /**
     * The first name of the member.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    firstName: string;
    /**
     * The first name of the member.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    lastName: string;
    /**
     * The personal email of the member.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    personalEmail?: string;
    /**
     * The URL of the member's profile picture.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    profilePictureUrl?: string;
    /**
     * The LinkedIn URL of the member.
     * @type {string}
     * @memberof LinkedinAuthDto
     */
    linkedinUrl?: string;
}

/**
 * Check if a given object implements the LinkedinAuthDto interface.
 */
export function instanceOfLinkedinAuthDto(value: object): value is LinkedinAuthDto {
    if (!('personId' in value) || value['personId'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function LinkedinAuthDtoFromJSON(json: any): LinkedinAuthDto {
    return LinkedinAuthDtoFromJSONTyped(json, false);
}

export function LinkedinAuthDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkedinAuthDto {
    if (json == null) {
        return json;
    }
    return {
        
        'personId': json['personId'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'personalEmail': json['personalEmail'] == null ? undefined : json['personalEmail'],
        'profilePictureUrl': json['profilePictureUrl'] == null ? undefined : json['profilePictureUrl'],
        'linkedinUrl': json['linkedinUrl'] == null ? undefined : json['linkedinUrl'],
    };
}

export function LinkedinAuthDtoToJSON(json: any): LinkedinAuthDto {
    return LinkedinAuthDtoToJSONTyped(json, false);
}

export function LinkedinAuthDtoToJSONTyped(value?: LinkedinAuthDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personId': value['personId'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'personalEmail': value['personalEmail'],
        'profilePictureUrl': value['profilePictureUrl'],
        'linkedinUrl': value['linkedinUrl'],
    };
}

