/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationAnalyticsEntity
 */
export interface LocationAnalyticsEntity {
    /**
     * 
     * @type {string}
     * @memberof LocationAnalyticsEntity
     */
    id: string;
    /**
     * The country of the location
     * @type {string}
     * @memberof LocationAnalyticsEntity
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof LocationAnalyticsEntity
     */
    countryCode?: string;
    /**
     * The city of the location
     * @type {string}
     * @memberof LocationAnalyticsEntity
     */
    city?: string;
    /**
     * The latitude of the location
     * @type {number}
     * @memberof LocationAnalyticsEntity
     */
    latitude?: number;
    /**
     * The longitude of the location
     * @type {number}
     * @memberof LocationAnalyticsEntity
     */
    longitude?: number;
}

/**
 * Check if a given object implements the LocationAnalyticsEntity interface.
 */
export function instanceOfLocationAnalyticsEntity(value: object): value is LocationAnalyticsEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function LocationAnalyticsEntityFromJSON(json: any): LocationAnalyticsEntity {
    return LocationAnalyticsEntityFromJSONTyped(json, false);
}

export function LocationAnalyticsEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationAnalyticsEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'country': json['country'] == null ? undefined : json['country'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'city': json['city'] == null ? undefined : json['city'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function LocationAnalyticsEntityToJSON(json: any): LocationAnalyticsEntity {
    return LocationAnalyticsEntityToJSONTyped(json, false);
}

export function LocationAnalyticsEntityToJSONTyped(value?: LocationAnalyticsEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'country': value['country'],
        'countryCode': value['countryCode'],
        'city': value['city'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

