/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkAsReviewedDto
 */
export interface MarkAsReviewedDto {
    /**
     * The id of the alumni to mark as reviewed
     * @type {string}
     * @memberof MarkAsReviewedDto
     */
    id: string;
}

/**
 * Check if a given object implements the MarkAsReviewedDto interface.
 */
export function instanceOfMarkAsReviewedDto(value: object): value is MarkAsReviewedDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MarkAsReviewedDtoFromJSON(json: any): MarkAsReviewedDto {
    return MarkAsReviewedDtoFromJSONTyped(json, false);
}

export function MarkAsReviewedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkAsReviewedDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function MarkAsReviewedDtoToJSON(json: any): MarkAsReviewedDto {
    return MarkAsReviewedDtoToJSONTyped(json, false);
}

export function MarkAsReviewedDtoToJSONTyped(value?: MarkAsReviewedDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

