/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MergeLocationsDto
 */
export interface MergeLocationsDto {
    /**
     * The location ids to merge
     * @type {Array<string>}
     * @memberof MergeLocationsDto
     */
    locationIds: Array<string>;
    /**
     * The location id to merge into
     * @type {string}
     * @memberof MergeLocationsDto
     */
    mergeIntoLocationId: string;
}

/**
 * Check if a given object implements the MergeLocationsDto interface.
 */
export function instanceOfMergeLocationsDto(value: object): value is MergeLocationsDto {
    if (!('locationIds' in value) || value['locationIds'] === undefined) return false;
    if (!('mergeIntoLocationId' in value) || value['mergeIntoLocationId'] === undefined) return false;
    return true;
}

export function MergeLocationsDtoFromJSON(json: any): MergeLocationsDto {
    return MergeLocationsDtoFromJSONTyped(json, false);
}

export function MergeLocationsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MergeLocationsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'locationIds': json['locationIds'],
        'mergeIntoLocationId': json['mergeIntoLocationId'],
    };
}

export function MergeLocationsDtoToJSON(json: any): MergeLocationsDto {
    return MergeLocationsDtoToJSONTyped(json, false);
}

export function MergeLocationsDtoToJSONTyped(value?: MergeLocationsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'locationIds': value['locationIds'],
        'mergeIntoLocationId': value['mergeIntoLocationId'],
    };
}

