/* tslint:disable */
/* eslint-disable */
/**
 * Alumni Feup API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PendingProfileDto
 */
export interface PendingProfileDto {
    /**
     * LinkedIn person ID (sub claim)
     * @type {string}
     * @memberof PendingProfileDto
     */
    personId: string;
    /**
     * 
     * @type {string}
     * @memberof PendingProfileDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PendingProfileDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof PendingProfileDto
     */
    personalEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof PendingProfileDto
     */
    profilePictureUrl?: string;
}

/**
 * Check if a given object implements the PendingProfileDto interface.
 */
export function instanceOfPendingProfileDto(value: object): value is PendingProfileDto {
    if (!('personId' in value) || value['personId'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function PendingProfileDtoFromJSON(json: any): PendingProfileDto {
    return PendingProfileDtoFromJSONTyped(json, false);
}

export function PendingProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'personId': json['personId'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'personalEmail': json['personalEmail'] == null ? undefined : json['personalEmail'],
        'profilePictureUrl': json['profilePictureUrl'] == null ? undefined : json['profilePictureUrl'],
    };
}

export function PendingProfileDtoToJSON(json: any): PendingProfileDto {
    return PendingProfileDtoToJSONTyped(json, false);
}

export function PendingProfileDtoToJSONTyped(value?: PendingProfileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personId': value['personId'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'personalEmail': value['personalEmail'],
        'profilePictureUrl': value['profilePictureUrl'],
    };
}

