/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SeniorityClassificationVo } from './SeniorityClassificationVo';
import {
    SeniorityClassificationVoFromJSON,
    SeniorityClassificationVoFromJSONTyped,
    SeniorityClassificationVoToJSON,
    SeniorityClassificationVoToJSONTyped,
} from './SeniorityClassificationVo';

/**
 * 
 * @export
 * @interface RoleMetadataVo
 */
export interface RoleMetadataVo {
    /**
     * The seniority level classification metadata
     * @type {SeniorityClassificationVo}
     * @memberof RoleMetadataVo
     */
    seniorityClassification?: SeniorityClassificationVo;
}

/**
 * Check if a given object implements the RoleMetadataVo interface.
 */
export function instanceOfRoleMetadataVo(value: object): value is RoleMetadataVo {
    return true;
}

export function RoleMetadataVoFromJSON(json: any): RoleMetadataVo {
    return RoleMetadataVoFromJSONTyped(json, false);
}

export function RoleMetadataVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleMetadataVo {
    if (json == null) {
        return json;
    }
    return {
        
        'seniorityClassification': json['seniority_classification'] == null ? undefined : SeniorityClassificationVoFromJSON(json['seniority_classification']),
    };
}

export function RoleMetadataVoToJSON(json: any): RoleMetadataVo {
    return RoleMetadataVoToJSONTyped(json, false);
}

export function RoleMetadataVoToJSONTyped(value?: RoleMetadataVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seniority_classification': SeniorityClassificationVoToJSON(value['seniorityClassification']),
    };
}

