/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobClassificationAnalyticsEntity } from './JobClassificationAnalyticsEntity';
import {
    JobClassificationAnalyticsEntityFromJSON,
    JobClassificationAnalyticsEntityFromJSONTyped,
    JobClassificationAnalyticsEntityToJSON,
    JobClassificationAnalyticsEntityToJSONTyped,
} from './JobClassificationAnalyticsEntity';
import type { CompanyAnalyticsEntity } from './CompanyAnalyticsEntity';
import {
    CompanyAnalyticsEntityFromJSON,
    CompanyAnalyticsEntityFromJSONTyped,
    CompanyAnalyticsEntityToJSON,
    CompanyAnalyticsEntityToJSONTyped,
} from './CompanyAnalyticsEntity';
import type { LocationAnalyticsEntity } from './LocationAnalyticsEntity';
import {
    LocationAnalyticsEntityFromJSON,
    LocationAnalyticsEntityFromJSONTyped,
    LocationAnalyticsEntityToJSON,
    LocationAnalyticsEntityToJSONTyped,
} from './LocationAnalyticsEntity';
import type { RoleMetadataVo } from './RoleMetadataVo';
import {
    RoleMetadataVoFromJSON,
    RoleMetadataVoFromJSONTyped,
    RoleMetadataVoToJSON,
    RoleMetadataVoToJSONTyped,
} from './RoleMetadataVo';
import type { RoleRawAnalyticsEntity } from './RoleRawAnalyticsEntity';
import {
    RoleRawAnalyticsEntityFromJSON,
    RoleRawAnalyticsEntityFromJSONTyped,
    RoleRawAnalyticsEntityToJSON,
    RoleRawAnalyticsEntityToJSONTyped,
} from './RoleRawAnalyticsEntity';

/**
 * 
 * @export
 * @interface RoleAnalyticsEntity
 */
export interface RoleAnalyticsEntity {
    /**
     * 
     * @type {string}
     * @memberof RoleAnalyticsEntity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoleAnalyticsEntity
     */
    alumniId: string;
    /**
     * 
     * @type {Date}
     * @memberof RoleAnalyticsEntity
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof RoleAnalyticsEntity
     */
    endDate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof RoleAnalyticsEntity
     */
    isCurrent: boolean;
    /**
     * 
     * @type {LocationAnalyticsEntity}
     * @memberof RoleAnalyticsEntity
     */
    location?: LocationAnalyticsEntity;
    /**
     * 
     * @type {CompanyAnalyticsEntity}
     * @memberof RoleAnalyticsEntity
     */
    company: CompanyAnalyticsEntity;
    /**
     * 
     * @type {string}
     * @memberof RoleAnalyticsEntity
     */
    seniorityLevel: RoleAnalyticsEntitySeniorityLevelEnum;
    /**
     * 
     * @type {JobClassificationAnalyticsEntity}
     * @memberof RoleAnalyticsEntity
     */
    jobClassification?: JobClassificationAnalyticsEntity;
    /**
     * 
     * @type {RoleRawAnalyticsEntity}
     * @memberof RoleAnalyticsEntity
     */
    roleRaw?: RoleRawAnalyticsEntity;
    /**
     * Whether the seniority level was accepted by the user
     * @type {boolean}
     * @memberof RoleAnalyticsEntity
     */
    wasSeniorityLevelAcceptedByUser?: boolean;
    /**
     * Whether the seniority level was modified by the user
     * @type {boolean}
     * @memberof RoleAnalyticsEntity
     */
    wasSeniorityLevelModifiedByUser?: boolean;
    /**
     * Whether the role is the main role of the user
     * @type {boolean}
     * @memberof RoleAnalyticsEntity
     */
    isMainRole?: boolean;
    /**
     * Whether the role is hidden in the user profile
     * @type {boolean}
     * @memberof RoleAnalyticsEntity
     */
    isHiddenInProfile?: boolean;
    /**
     * The metadata of the role
     * @type {RoleMetadataVo}
     * @memberof RoleAnalyticsEntity
     */
    metadata?: RoleMetadataVo;
}


/**
 * @export
 */
export const RoleAnalyticsEntitySeniorityLevelEnum = {
    Intern: 'INTERN',
    EntryLevel: 'ENTRY_LEVEL',
    Associate: 'ASSOCIATE',
    MidSeniorLevel: 'MID_SENIOR_LEVEL',
    Director: 'DIRECTOR',
    Executive: 'EXECUTIVE',
    CLevel: 'C_LEVEL'
} as const;
export type RoleAnalyticsEntitySeniorityLevelEnum = typeof RoleAnalyticsEntitySeniorityLevelEnum[keyof typeof RoleAnalyticsEntitySeniorityLevelEnum];


/**
 * Check if a given object implements the RoleAnalyticsEntity interface.
 */
export function instanceOfRoleAnalyticsEntity(value: object): value is RoleAnalyticsEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('alumniId' in value) || value['alumniId'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('isCurrent' in value) || value['isCurrent'] === undefined) return false;
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('seniorityLevel' in value) || value['seniorityLevel'] === undefined) return false;
    return true;
}

export function RoleAnalyticsEntityFromJSON(json: any): RoleAnalyticsEntity {
    return RoleAnalyticsEntityFromJSONTyped(json, false);
}

export function RoleAnalyticsEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleAnalyticsEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'alumniId': json['alumniId'],
        'startDate': (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'isCurrent': json['isCurrent'],
        'location': json['location'] == null ? undefined : LocationAnalyticsEntityFromJSON(json['location']),
        'company': CompanyAnalyticsEntityFromJSON(json['company']),
        'seniorityLevel': json['seniorityLevel'],
        'jobClassification': json['jobClassification'] == null ? undefined : JobClassificationAnalyticsEntityFromJSON(json['jobClassification']),
        'roleRaw': json['roleRaw'] == null ? undefined : RoleRawAnalyticsEntityFromJSON(json['roleRaw']),
        'wasSeniorityLevelAcceptedByUser': json['wasSeniorityLevelAcceptedByUser'] == null ? undefined : json['wasSeniorityLevelAcceptedByUser'],
        'wasSeniorityLevelModifiedByUser': json['wasSeniorityLevelModifiedByUser'] == null ? undefined : json['wasSeniorityLevelModifiedByUser'],
        'isMainRole': json['isMainRole'] == null ? undefined : json['isMainRole'],
        'isHiddenInProfile': json['isHiddenInProfile'] == null ? undefined : json['isHiddenInProfile'],
        'metadata': json['metadata'] == null ? undefined : RoleMetadataVoFromJSON(json['metadata']),
    };
}

export function RoleAnalyticsEntityToJSON(json: any): RoleAnalyticsEntity {
    return RoleAnalyticsEntityToJSONTyped(json, false);
}

export function RoleAnalyticsEntityToJSONTyped(value?: RoleAnalyticsEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'alumniId': value['alumniId'],
        'startDate': ((value['startDate']).toISOString()),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString()),
        'isCurrent': value['isCurrent'],
        'location': LocationAnalyticsEntityToJSON(value['location']),
        'company': CompanyAnalyticsEntityToJSON(value['company']),
        'seniorityLevel': value['seniorityLevel'],
        'jobClassification': JobClassificationAnalyticsEntityToJSON(value['jobClassification']),
        'roleRaw': RoleRawAnalyticsEntityToJSON(value['roleRaw']),
        'wasSeniorityLevelAcceptedByUser': value['wasSeniorityLevelAcceptedByUser'],
        'wasSeniorityLevelModifiedByUser': value['wasSeniorityLevelModifiedByUser'],
        'isMainRole': value['isMainRole'],
        'isHiddenInProfile': value['isHiddenInProfile'],
        'metadata': RoleMetadataVoToJSON(value['metadata']),
    };
}

