/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleListDto
 */
export interface RoleListDto {
    /**
     * The ESCO title of the role
     * @type {string}
     * @memberof RoleListDto
     */
    title: string;
    /**
     * The level of classification of the role, 1 being a more general role and 2 being a more specific role
     * @type {number}
     * @memberof RoleListDto
     */
    level: number;
    /**
     * The ESCO code of the role
     * @type {string}
     * @memberof RoleListDto
     */
    code: string;
    /**
     * The number of roles classified with this role
     * @type {number}
     * @memberof RoleListDto
     */
    roleCount: number;
}

/**
 * Check if a given object implements the RoleListDto interface.
 */
export function instanceOfRoleListDto(value: object): value is RoleListDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('roleCount' in value) || value['roleCount'] === undefined) return false;
    return true;
}

export function RoleListDtoFromJSON(json: any): RoleListDto {
    return RoleListDtoFromJSONTyped(json, false);
}

export function RoleListDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleListDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'level': json['level'],
        'code': json['code'],
        'roleCount': json['roleCount'],
    };
}

export function RoleListDtoToJSON(json: any): RoleListDto {
    return RoleListDtoToJSONTyped(json, false);
}

export function RoleListDtoToJSONTyped(value?: RoleListDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'level': value['level'],
        'code': value['code'],
        'roleCount': value['roleCount'],
    };
}

