/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataPointDto } from './DataPointDto';
import {
    DataPointDtoFromJSON,
    DataPointDtoFromJSONTyped,
    DataPointDtoToJSON,
    DataPointDtoToJSONTyped,
} from './DataPointDto';

/**
 * 
 * @export
 * @interface SeniorityListItemDto
 */
export interface SeniorityListItemDto {
    /**
     * The name of the seniority level
     * @type {string}
     * @memberof SeniorityListItemDto
     */
    name: SeniorityListItemDtoNameEnum;
    /**
     * The number of roles with this seniority level
     * @type {number}
     * @memberof SeniorityListItemDto
     */
    count: number;
    /**
     * The trend of the seniority level
     * @type {Array<DataPointDto>}
     * @memberof SeniorityListItemDto
     */
    trend: Array<DataPointDto>;
}


/**
 * @export
 */
export const SeniorityListItemDtoNameEnum = {
    Intern: 'INTERN',
    EntryLevel: 'ENTRY_LEVEL',
    Associate: 'ASSOCIATE',
    MidSeniorLevel: 'MID_SENIOR_LEVEL',
    Director: 'DIRECTOR',
    Executive: 'EXECUTIVE',
    CLevel: 'C_LEVEL'
} as const;
export type SeniorityListItemDtoNameEnum = typeof SeniorityListItemDtoNameEnum[keyof typeof SeniorityListItemDtoNameEnum];


/**
 * Check if a given object implements the SeniorityListItemDto interface.
 */
export function instanceOfSeniorityListItemDto(value: object): value is SeniorityListItemDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('trend' in value) || value['trend'] === undefined) return false;
    return true;
}

export function SeniorityListItemDtoFromJSON(json: any): SeniorityListItemDto {
    return SeniorityListItemDtoFromJSONTyped(json, false);
}

export function SeniorityListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeniorityListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'count': json['count'],
        'trend': ((json['trend'] as Array<any>).map(DataPointDtoFromJSON)),
    };
}

export function SeniorityListItemDtoToJSON(json: any): SeniorityListItemDto {
    return SeniorityListItemDtoToJSONTyped(json, false);
}

export function SeniorityListItemDtoToJSONTyped(value?: SeniorityListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'count': value['count'],
        'trend': ((value['trend'] as Array<any>).map(DataPointDtoToJSON)),
    };
}

