/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeniorityLevelAcceptedByUserDto
 */
export interface SeniorityLevelAcceptedByUserDto {
    /**
     * Whether the seniority level was accepted by the user
     * @type {boolean}
     * @memberof SeniorityLevelAcceptedByUserDto
     */
    wasSeniorityLevelAcceptedByUser: boolean;
}

/**
 * Check if a given object implements the SeniorityLevelAcceptedByUserDto interface.
 */
export function instanceOfSeniorityLevelAcceptedByUserDto(value: object): value is SeniorityLevelAcceptedByUserDto {
    if (!('wasSeniorityLevelAcceptedByUser' in value) || value['wasSeniorityLevelAcceptedByUser'] === undefined) return false;
    return true;
}

export function SeniorityLevelAcceptedByUserDtoFromJSON(json: any): SeniorityLevelAcceptedByUserDto {
    return SeniorityLevelAcceptedByUserDtoFromJSONTyped(json, false);
}

export function SeniorityLevelAcceptedByUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeniorityLevelAcceptedByUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'wasSeniorityLevelAcceptedByUser': json['wasSeniorityLevelAcceptedByUser'],
    };
}

export function SeniorityLevelAcceptedByUserDtoToJSON(json: any): SeniorityLevelAcceptedByUserDto {
    return SeniorityLevelAcceptedByUserDtoToJSONTyped(json, false);
}

export function SeniorityLevelAcceptedByUserDtoToJSONTyped(value?: SeniorityLevelAcceptedByUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wasSeniorityLevelAcceptedByUser': value['wasSeniorityLevelAcceptedByUser'],
    };
}

