/* tslint:disable */
/* eslint-disable */
/**
 * API
 * API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateClassificationDto
 */
export interface UpdateClassificationDto {
    /**
     * The new ESCO classification of the role
     * @type {string}
     * @memberof UpdateClassificationDto
     */
    escoClassificationId: string;
}

/**
 * Check if a given object implements the UpdateClassificationDto interface.
 */
export function instanceOfUpdateClassificationDto(value: object): value is UpdateClassificationDto {
    if (!('escoClassificationId' in value) || value['escoClassificationId'] === undefined) return false;
    return true;
}

export function UpdateClassificationDtoFromJSON(json: any): UpdateClassificationDto {
    return UpdateClassificationDtoFromJSONTyped(json, false);
}

export function UpdateClassificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateClassificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'escoClassificationId': json['escoClassificationId'],
    };
}

export function UpdateClassificationDtoToJSON(json: any): UpdateClassificationDto {
    return UpdateClassificationDtoToJSONTyped(json, false);
}

export function UpdateClassificationDtoToJSONTyped(value?: UpdateClassificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'escoClassificationId': value['escoClassificationId'],
    };
}

