/* tslint:disable */
/* eslint-disable */
/**
 * Alumni Feup API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertPermissionDto
 */
export interface UpsertPermissionDto {
    /**
     * The ID of the alumni to assign permissions to
     * @type {string}
     * @memberof UpsertPermissionDto
     */
    userId: string;
    /**
     * The resource the permission applies to
     * @type {string}
     * @memberof UpsertPermissionDto
     */
    resource: string;
    /**
     * The actions to grant on the resource
     * @type {Array<string>}
     * @memberof UpsertPermissionDto
     */
    actions: Array<string>;
}

/**
 * Check if a given object implements the UpsertPermissionDto interface.
 */
export function instanceOfUpsertPermissionDto(value: object): value is UpsertPermissionDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('resource' in value) || value['resource'] === undefined) return false;
    if (!('actions' in value) || value['actions'] === undefined) return false;
    return true;
}

export function UpsertPermissionDtoFromJSON(json: any): UpsertPermissionDto {
    return UpsertPermissionDtoFromJSONTyped(json, false);
}

export function UpsertPermissionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertPermissionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'resource': json['resource'],
        'actions': json['actions'],
    };
}

export function UpsertPermissionDtoToJSON(json: any): UpsertPermissionDto {
    return UpsertPermissionDtoToJSONTyped(json, false);
}

export function UpsertPermissionDtoToJSONTyped(value?: UpsertPermissionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'resource': value['resource'],
        'actions': value['actions'],
    };
}

