import { SORT_BY, SORT_ORDER } from './enum';

export const DEFAULT_QUERY_LIMIT = Number.MAX_SAFE_INTEGER;
export const DEFAULT_QUERY_OFFSET = 0;
export const DEFAULT_QUERY_SORT_BY = SORT_BY.COUNT;
export const DEFAULT_QUERY_SORT_ORDER = SORT_ORDER.DESC;

const RESEARCH_SERVICES_INDUSTRY_ID = '5ef5c029-b671-4957-b33d-28a959e4dd9c';
const HIGHER_EDUCATION_INDUSTRY_ID = 'b34884d6-fd6a-4931-9528-ed9330305beb';

export const EXCLUDED_INDUSTRIES = [
  RESEARCH_SERVICES_INDUSTRY_ID,
  HIGHER_EDUCATION_INDUSTRY_ID,
];

export const PORTUGAL_COUNTRY_CODE = 'PT';
