name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint PR Title
        run: echo "${{ github.event.pull_request.title }}" | npx --yes commitlint --config commitlint.config.js
